DS-Corner-Page/cornerpage_front

src/components/project/projectDetail/Detail.js
src/components/project/projectDetail/Detail.style.js
src/components/project/projectList/ProjectList.style.js
src/components/project/projectNumber/ProjectNumber.js
src/components/project/projectNumber/ProjectNumber.style.js
src/components/title/gradientBar/GradientBar.style.js
src/components/title/title/Title.style.js
src/core/project_data.json

💄 Design: 작품 상세 페이지 반응형 구현

---

src/components/project/projectDetail/Detail.style.js

💄 Design: 상세 페이지 오른쪽 여백 추가

---

src/components/project/projectDetail/Detail.style.js
src/components/project/projectGroup/ProjectGroup.style.js
src/components/project/singleProject/SingleProject.style.js

💄 Design: 모바일 반응형 수정

---

.github/workflows/deploy.yml
build.sh

🚀 Deploy: cicd 배포

---

.github/workflows/deploy.yml

🐛 Fix: username, repository name 수정

---

src/components/project/projectDetail/Detail.style.js

💄 Design: 발표 자료 반응형 추가

---

src/components/project/projectDetail/Detail.js

🐛 Fix: 상세 조회 페이지에서 뒤로가기 누르면 목록으로 이동

---

src/components/project/projectNumber/ProjectNumber.js
src/components/project/projectNumber/ProjectNumber.style.js

💄 Design: 메뉴바 디자인 수정

---

src/components/home/homeProjectSlider/HomeProjectSlider.js

슬라이드는 계속 움직이고 마우스 올리면 멈추도록 변경
#6 
프로젝트 슬라이드 동작 수정 
마우스 올리면 이동 => 계속 이동하며 마우스 올리면 멈춤
슬라이드 후 첫 이미지 반복될 때 갑자기 위치 이동하는 것처럼 보이는 거 수정해야 할 듯

♻️ Refactor: 슬라이드 동작 방식 변경

---

src/components/generationList/GenerationList.css
src/components/generationList/GenerationList.js
src/components/interview/interviewList/InterviewLIst.style.js
src/components/interview/interviewList/InterviewList.js
src/components/interview/projectNumber/projectNumber.js
src/components/interview/projectNumber/projectNumber.style.js
src/components/title/title/Title.js
src/page/About.js
src/page/Interview.js
src/styles/About.style.js

feat: About & Interview 내용만 완성

---

src/components/project/projectList/ProjectList.style.js
src/components/title/title/Title.style.js
src/styles/GalleryStyle.js

💄 Design: 제트플립 깨짐 현상 해결 

---

src/components/home/homeProjectSlider/HomeProjectSlider.js
src/components/home/homeProjectSlider/HomeProjectSlider.style.js

🐛 Fix: 슬라이드 애니메이션 수정

---

src/components/home/hackathonImg/HackathonImg.style.js
src/components/home/mainBar/MainBar.style.js
src/components/home/mainGroup/MainGroup.style.js

💄 Design: 막대바 반응형 수정

---

public/data/project_data.json

🐛 Fix: Code Ground 소개 멘트 수정

---

src/components/project/projectDetail/Detail.js
src/components/project/projectDisplay/ProjectDisplay.js

♻️ Refactor: 로딩 메세지 제거 

---

src/components/home/homeDisplay/HomeDisplay.js

🐛 Fix: 오타 수정

---

src/components/generationList/GenerationList.css
src/page/Interview.js

Fix: 인터뷰 css 수정

---

src/components/generationList/GenerationList.css

Fix: 인터뷰 바 css 수정

---

src/components/title/gradientBar/GradientBar.style.js
src/components/title/title/Title.style.js

:bug: Fix: 타이틀 줄 바뀜 문제 해결

---

src/components/title/title/Title.js
src/page/About.js
src/page/Gallery.js
src/page/Interview.js
src/page/Project.js

:lipstick: Design: 타이틀 바 색상 변경
